#!/usr/bin/env python3
"""Run the complete offline development and clean-room package validation pipeline."""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve(strict=True).parents[1]
SOURCE_ROOT = REPO_ROOT / "src" / "super-review"
FORBIDDEN_PARTS = {"__pycache__", ".git", ".venv"}
FORBIDDEN_SUFFIXES = {".pyc", ".pyo"}


def _run(command: list[str], cwd: Path = REPO_ROOT) -> None:
    print("+", " ".join(command), flush=True)
    environment = os.environ.copy()
    environment["PYTHONDONTWRITEBYTECODE"] = "1"
    subprocess.run(command, cwd=cwd, check=True, env=environment)


def _remove_generated_bytecode() -> None:
    """Remove Python cache files created by nested isolated test processes."""
    for cache in sorted(REPO_ROOT.rglob("__pycache__"), reverse=True):
        if cache.is_dir():
            shutil.rmtree(cache)
    for suffix in ("*.pyc", "*.pyo"):
        for path in REPO_ROOT.rglob(suffix):
            path.unlink(missing_ok=True)


def _check_tree() -> None:
    """Verify that required repository files are present and that the tree contains no symbolic links or generated bytecode."""
    required = [
        REPO_ROOT / "AGENTS.md",
        REPO_ROOT / "README.md",
        REPO_ROOT / "VERSION",
        REPO_ROOT / ".agents" / "plugins" / "marketplace.json",
        REPO_ROOT / ".claude-plugin" / "marketplace.json",
        REPO_ROOT / ".cursor-plugin" / "plugin.json",
        REPO_ROOT / ".github" / "plugin" / "marketplace.json",
        REPO_ROOT / "src" / ".claude-plugin" / "plugin.json",
        REPO_ROOT / "src" / ".codex-plugin" / "plugin.json",
        REPO_ROOT / "src" / "client-adapters" / "commands" / "super-review.md",
        REPO_ROOT
        / "src"
        / "client-adapters"
        / "cursor"
        / "commands"
        / "super-review.md",
        REPO_ROOT / "src" / "plugin.json",
        REPO_ROOT / "src" / "LICENSE",
        SOURCE_ROOT / "LICENSE",
        SOURCE_ROOT / "SKILL.md",
        SOURCE_ROOT / "agents" / "openai.yaml",
        SOURCE_ROOT / "scripts" / "validate_findings.py",
        SOURCE_ROOT / "scripts" / "commit_findings.py",
        SOURCE_ROOT / "tests" / "run_tests.py",
    ]
    missing = [
        str(path.relative_to(REPO_ROOT)) for path in required if not path.is_file()
    ]
    if missing:
        raise RuntimeError(f"missing required files: {missing}")

    for path in REPO_ROOT.rglob("*"):
        relative = path.relative_to(REPO_ROOT)
        if any(part in FORBIDDEN_PARTS for part in relative.parts):
            continue
        info = path.lstat()
        if stat.S_ISLNK(info.st_mode):
            raise RuntimeError(f"repository contains a symbolic link: {relative}")
        if path.is_file() and path.suffix in FORBIDDEN_SUFFIXES:
            raise RuntimeError(f"repository contains generated bytecode: {relative}")


def _check_python_syntax() -> None:
    for path in sorted(REPO_ROOT.rglob("*.py"), key=lambda item: item.as_posix()):
        if any(part in FORBIDDEN_PARTS for part in path.relative_to(REPO_ROOT).parts):
            continue
        source = path.read_bytes()
        try:
            compile(source, str(path), "exec", dont_inherit=True)
        except (SyntaxError, ValueError) as exc:
            raise RuntimeError(f"Python syntax check failed for {path}: {exc}") from exc


def _check_prompt_provenance() -> None:
    prompt = REPO_ROOT / "docs" / "ORIGINAL_REVIEW_PROMPT.md"
    checksum_file = REPO_ROOT / "docs" / "ORIGINAL_REVIEW_PROMPT.sha256"
    expected = checksum_file.read_text(encoding="utf-8").split()[0]
    actual = hashlib.sha256(prompt.read_bytes()).hexdigest()
    if actual != expected:
        raise RuntimeError(
            f"original prompt checksum mismatch: expected {expected}, actual {actual}"
        )


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--spec",
        action="store_true",
        help="also require the external skills-ref validator",
    )
    return parser


def main() -> int:
    args = _parser().parse_args()
    _remove_generated_bytecode()
    try:
        _check_tree()
        _check_python_syntax()
        _check_prompt_provenance()

        _run([sys.executable, "-I", "-B", str(REPO_ROOT / "tests" / "run_tests.py")])
        _run(
            [sys.executable, "-I", "-B", str(SOURCE_ROOT / "tests" / "run_tests.py")],
            SOURCE_ROOT,
        )
        _run(
            [
                sys.executable,
                "-I",
                "-B",
                str(SOURCE_ROOT / "scripts" / "validate_findings.py"),
                "--self-test",
            ],
            SOURCE_ROOT,
        )

        with tempfile.TemporaryDirectory(prefix="super-review-check-") as directory:
            temporary = Path(directory)
            artifact = temporary / "super-review-skill.zip"
            _run(
                [
                    sys.executable,
                    str(REPO_ROOT / "scripts" / "build.py"),
                    "--output",
                    str(artifact),
                ]
            )
            _run(
                [
                    sys.executable,
                    str(REPO_ROOT / "scripts" / "verify_dist.py"),
                    str(artifact),
                ]
            )

        if args.spec:
            _run([sys.executable, str(REPO_ROOT / "scripts" / "spec_validate.py")])

        print("all offline checks passed")
        return 0
    finally:
        _remove_generated_bytecode()


if __name__ == "__main__":
    raise SystemExit(main())
